### ISSUE TITLE
Clickable nodes

### ISSUE THREAD

**Issue by johankson** [TrueCommerce/MermaidJS.Blazor#10]
Hi!

Another question regarding making nodes clickable. I hade to tweak `MermaidDiagramInterop.js` to adjust the security level to make the click callback to work.

Is there another way that I'm missing? :)

```js
function initializeGlobals() {
    window.mermaidDiagramBlazorOptions.securityLevel = "loose"; // <-- Had to add this
    console.log("initializeGlobals", window.mermaidDiagramBlazorOptions);
    function loadMermaid() {
        return new Promise((resolve) => { ...

```

**Comment by DotJoshJohnson** [comment]
You can set the security level when you call `AddMermaidJS()` on your service collection. See [the demo project](https://github.com/TrueCommerce/MermaidJS.Blazor/blob/305b2374ee0c8d16b27df3dd550c5e6305f0e191/demo/MermaidJS.Blazor.Demo/Program.cs#L23) for an example.

**Comment by johankson** [comment]
Excellent! Makes a lot more sense than my fix!
